services:
  postgres:
    image: postgres:16-alpine
    container_name: n8n-lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - n8n_lab_network

  mock-api:
    build:
      context: ./mock-api
      dockerfile: Dockerfile
    container_name: n8n-lab-mock-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${MOCK_API_PORT}
      TZ: ${TZ}
    ports:
      - "${MOCK_API_PORT}:${MOCK_API_PORT}"
    volumes:
      - ./mock-api:/app
      - /app/node_modules
      - ./shared:/app/shared
    networks:
      - n8n_lab_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-lab
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      mock-api:
        condition: service_started
    ports:
      - "${N8N_PORT}:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: http://localhost:${N8N_PORT}/

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_USER_MANAGEMENT_JWT_SECRET: ${N8N_USER_MANAGEMENT_JWT_SECRET}

      N8N_LOG_LEVEL: ${N8N_LOG_LEVEL}
      N8N_LOG_OUTPUT: ${N8N_LOG_OUTPUT}

      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}

      TZ: ${TZ}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}

      MOCK_API_URL: ${MOCK_API_URL}
      APP_ENV: ${APP_ENV}

      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: 168

      META_GRAPH_API_VERSION: ${META_GRAPH_API_VERSION}
      META_IG_USER_ID: ${META_IG_USER_ID}
      META_IG_ACCESS_TOKEN: ${META_IG_ACCESS_TOKEN}
      N8N_BLOCK_ENV_ACCESS_IN_NODE: ${N8N_BLOCK_ENV_ACCESS_IN_NODE}

      NODE_FUNCTION_ALLOW_BUILTIN: fs

    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/files/workflows
      - ./shared:/files/shared
      - ./scripts:/files/scripts
    networks:
      - n8n_lab_network

volumes:
  postgres_data:
  n8n_data:

networks:
  n8n_lab_network:
    driver: bridge